import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

class ApptextStyle {
  // regular
  static TextStyle style10Reg =
      TextStyle(fontSize: 10.sp, fontWeight: FontWeight.w300);
  static TextStyle style11Reg =
      TextStyle(fontSize: 11.sp, fontWeight: FontWeight.w300);
  static TextStyle style12Reg =
      TextStyle(fontSize: 12.sp, fontWeight: FontWeight.w300);
  static TextStyle style13Reg =
      TextStyle(fontSize: 13.sp, fontWeight: FontWeight.w300);
  static TextStyle style14Reg =
      TextStyle(fontSize: 14.sp, fontWeight: FontWeight.w300);
  static TextStyle style15Reg =
      TextStyle(fontSize: 15.sp, fontWeight: FontWeight.w300);
  static TextStyle style16Reg =
      TextStyle(fontSize: 16.sp, fontWeight: FontWeight.w300);
  static TextStyle style17Reg =
      TextStyle(fontSize: 17.sp, fontWeight: FontWeight.w300);
  static TextStyle style18Reg =
      TextStyle(fontSize: 18.sp, fontWeight: FontWeight.w300);
  static TextStyle style19Reg =
      TextStyle(fontSize: 19.sp, fontWeight: FontWeight.w300);
  static TextStyle style20Reg =
      TextStyle(fontSize: 20.sp, fontWeight: FontWeight.w300);
  static TextStyle style21Reg =
      TextStyle(fontSize: 21.sp, fontWeight: FontWeight.w300);
  static TextStyle style22Reg =
      TextStyle(fontSize: 22.sp, fontWeight: FontWeight.w300);
  static TextStyle style23Reg =
      TextStyle(fontSize: 23.sp, fontWeight: FontWeight.w300);
  static TextStyle style24Reg =
      TextStyle(fontSize: 24.sp, fontWeight: FontWeight.w300);
  static TextStyle style25Reg =
      TextStyle(fontSize: 25.sp, fontWeight: FontWeight.w300);
  //medium
  static TextStyle style10Med =
      TextStyle(fontSize: 10.sp, fontWeight: FontWeight.w500);
  static TextStyle style11Med =
      TextStyle(fontSize: 11.sp, fontWeight: FontWeight.w500);
  static TextStyle style12Med =
      TextStyle(fontSize: 12.sp, fontWeight: FontWeight.w500);
  static TextStyle style13Med =
      TextStyle(fontSize: 13.sp, fontWeight: FontWeight.w500);
  static TextStyle style14Med =
      TextStyle(fontSize: 14.sp, fontWeight: FontWeight.w500);
  static TextStyle style15Med =
      TextStyle(fontSize: 15.sp, fontWeight: FontWeight.w500);
  static TextStyle style16Med =
      TextStyle(fontSize: 16.sp, fontWeight: FontWeight.w500);
  static TextStyle style17Med =
      TextStyle(fontSize: 17.sp, fontWeight: FontWeight.w500);
  static TextStyle style18Med =
      TextStyle(fontSize: 18.sp, fontWeight: FontWeight.w500);
  static TextStyle style19Med =
      TextStyle(fontSize: 19.sp, fontWeight: FontWeight.w500);
  static TextStyle style20Med =
      TextStyle(fontSize: 20.sp, fontWeight: FontWeight.w500);
  static TextStyle style21Med =
      TextStyle(fontSize: 21.sp, fontWeight: FontWeight.w500);
  static TextStyle style22Med =
      TextStyle(fontSize: 22.sp, fontWeight: FontWeight.w500);
  static TextStyle style23Med =
      TextStyle(fontSize: 23.sp, fontWeight: FontWeight.w500);
  static TextStyle style24Med =
      TextStyle(fontSize: 24.sp, fontWeight: FontWeight.w500);
  static TextStyle style25Med =
      TextStyle(fontSize: 25.sp, fontWeight: FontWeight.w500);
  //bold
  static TextStyle style10bold =
      TextStyle(fontSize: 10.sp, fontWeight: FontWeight.w700);
  static TextStyle style11bold =
      TextStyle(fontSize: 11.sp, fontWeight: FontWeight.w700);
  static TextStyle style12bold =
      TextStyle(fontSize: 12.sp, fontWeight: FontWeight.w700);
  static TextStyle style13bold =
      TextStyle(fontSize: 13.sp, fontWeight: FontWeight.w700);
  static TextStyle style14bold =
      TextStyle(fontSize: 14.sp, fontWeight: FontWeight.w700);
  static TextStyle style15bold =
      TextStyle(fontSize: 15.sp, fontWeight: FontWeight.w700);
  static TextStyle style16bold =
      TextStyle(fontSize: 16.sp, fontWeight: FontWeight.w700);
  static TextStyle style17bold =
      TextStyle(fontSize: 17.sp, fontWeight: FontWeight.w700);
  static TextStyle style18bold =
      TextStyle(fontSize: 18.sp, fontWeight: FontWeight.w700);
  static TextStyle style19bold =
      TextStyle(fontSize: 19.sp, fontWeight: FontWeight.w700);
  static TextStyle style20bold =
      TextStyle(fontSize: 20.sp, fontWeight: FontWeight.w700);
  static TextStyle style21bold =
      TextStyle(fontSize: 21.sp, fontWeight: FontWeight.w700);
  static TextStyle style22bold =
      TextStyle(fontSize: 22.sp, fontWeight: FontWeight.w700);
  static TextStyle style23bold =
      TextStyle(fontSize: 23.sp, fontWeight: FontWeight.w700);
  static TextStyle style24bold =
      TextStyle(fontSize: 24.sp, fontWeight: FontWeight.w700);
  static TextStyle style25bold =
      TextStyle(fontSize: 25.sp, fontWeight: FontWeight.w700);
}
